### PR TITLE
Fix the build with ponyc 0.20+ & Travis-CI config

### PR DESCRIPTION
**Pull request by d-led**
Hi! Latest (0.21) ponyc fails to build the library with the error:

```
.deps\jemc\pony-zmq\zmq\socket_options.pony:55:5: match is exhaustive, the else clause is unreachable
    match this_opt | let optval: SocketOptionWithValue =>
    ^
    Info:
    .deps\jemc\pony-zmq\zmq\socket_options.pony:68:7: unreachable code
          false
          ^
```

this commit removes the `else` clause and adds a CI config for future PRs. For it to be effective, you'll need to replace the badge url with yours :).

Alternatively, pony could be installed directly in the travis config instead of running the build & test in a docker container.

Perhaps, the whole match expression should be eliminated. This was a quick fix to build a toy example

### CODE REVIEW

**Review by jemc — COMMENTED** [review]
Thanks for reaching out!

If we're going to use docker for CI, I'd prefer to move and/or rename the `Dockerfile` and `docker-compose.yml` to make it clear that they are meant for CI purposes, rather than users possibly getting confused about trying to use them for other purposes.

Note that if the `Dockerfile` filename is changed, you can specify it explicitly in the `docker-compose.yml`. And if the `docker-compose.yml` filename is changed, note that the `docker-compose` command accepts a `-f` argument to set that explicitly as well.

**Comment by d-led** [comment]
@jemc sure! I'll see if I can convince the Travis runner to install latest pony. If so, I'll get rid of the Docker config.

**Comment by jemc** [comment]
One more note to mention - note that I have two CI-related tasks in the Makefile already:
https://github.com/jemc/pony-zmq/blob/fe8997acc1817db7192596ee4a43de40d36f983c/Makefile#L26-L31

I'd prefer to use these as the basis for Travis CI runs.

I have been using them previously for a self-hosted Concourse CI instance, but I've grown weary of maintaining that instance, and I'm open to getting rid of it in favor of Travis CI, now that I know I can use [Travis cron jobs](https://docs.travis-ci.com/user/cron-jobs/) to do daily runs against `ponyc`'s `master` branch, as I was doing on Concourse CI. That's not something I'm saying you should add in this PR - it's just the general goal I'd be working toward.

**Comment by d-led** [comment]
ok! As I'm trying out, let's see if I can use those in the config

**Comment by d-led** [comment]
will let you know when it's "ready to squash or reject"

**Pull request closed without merging**
